### ISSUE TITLE
Defining the GT

### ISSUE THREAD

**Issue by bashar-tom** [chengricky/PanoramicScenePlaceRecognition#1]
Hi @chengricky ,
Thank you for providing the code for this work. 
I have a question about the definition of the Ground Truth. In the code, it seems that you havent used the GPS tags. Shouldn't we be using it? two images taken at the same place when we revisit the same place will be similar but have an index difference more than 10 frames. Also, in the data set, it is noticeable that when the car stops, there are somehow over 100 frames that are too similar to each other and they should be defined as the same place. 
Also, using a window of frames means that there will be always a GT for each of the query images and in your paper and in the code you check if the GT is empty.
The last question is about the F1 score which is published in the paper. I do not see its calculation in [PlaceRecognitionMain](https://github.com/chengricky/PanoramicScenePlaceRecognition/blob/master/PlaceRecognitionMain.py)
thanks in advance
Bashar

**Comment by chengricky** [comment]
Thanks for your attention to my work.
Actually, we use GNSS labels in our self-collected dataset and MOLP dataset. I am not clear which dataset you refer to. The self-collected dataset will be publicly available later. As for MOLP,  acturally we rearrange the dataset, we have more details [here](http://www.wangkaiwei.org/file/publications/thesis2019_shufei.pdf)  (if you understand Chinese :D )
As for the window of frame, we have thresholding operation to get rid of the low-confidence results.
The F1 score is not achieved here, because we have not organized all of the codes.
The intact codes and dataset will be available here soon:
[https://github.com/chengricky/PAL/](https://github.com/chengricky/PAL/)

Do not hesitate to contact me, if you have more questions.

**Comment by bashar-tom** [comment]
Thank you for your answer, 

Sorry I was not so clear. I meant the MOLP dataset.
unluckily I can't understand Chinese, but it would be so helpful if you explain the rearranging process of the dataset. This also means, that you haven't used the GPS tags of the images? 
Can't you define a radius using the GPS tags to define the GT?

**Comment by chengricky** [comment]
> Thank you for your answer,
> 
> Sorry I was not so clear. I meant the MOLP dataset.
> unluckily I can't understand Chinese, but it would be so helpful if you explain the rearranging process of the dataset. This also means, that you haven't used the GPS tags of the images?
> Can't you define a radius using the GPS tags to define the GT?

As we described in arXiv:1905.05425, the forward and backward of Summer Evening in Route A are used. The forward sequence is composed of 7,060 images, and the backward one is composed of 4,993 images. We sample 499 backward images from the sequence as query images, and we set the database image with the nearest GPS label as the ground truth of each query.
